### ISSUE TITLE
Any reason why Italian passports aren't compatible?

### ISSUE THREAD

**Issue by elchiapp** [UBIC-repo/core#16]
All EU passports should follow pretty much the same standard AFAIK. If so would you mind pointing me towards a good place to start contributing? Thanks!

**Comment by rgex** [comment]
Hi,
We don't have enough data about Italian passports to know if they are compatible.
If you want to help, you can scan your passport with the [Bondi passport reader App](https://play.google.com/store/apps/details?id=bondi.nfcPassportReader.jan.mrtd2&hl=de) on Android.
It is sending us technical data about the scanned passport (Document Signing Certificate and date of expiry).

**Comment by kseistrup** [comment]
Scanned a DK passport ok.

**Comment by ubicorn** [comment]
Danish passports will be added soon, Italian passports are currently "problematic"

**Comment by elchiapp** [comment]
Ok I'll close this (unless you feel like expanding on what the issue is, maybe I could help?). Thanks!

**Comment by rgex** [comment]
Italian passports might work now. But note that the passport might need up to one and and half year of validity left to generate coins.
This is because the DSC Certificates are only issued every 12 to 18 months in Italy instead of the 3 months that are recommended.
