### ISSUE TITLE
Unable to register German passport (IOS)

### ISSUE THREAD

**Issue by phaitonican** [UBIC-repo/core#21]
Entered everything correctly, after starting the scan it says "Reading failed, check the passport number and so on...". Anyone else having this issue?

**Comment by rgex** [comment]
Hi, which iPhone do you use? How old is the passport?

**Comment by phaitonican** [comment]
iPhone 8. It actually support this. The passport is new, I can use German App to Scan my passport it works.

**Comment by rgex** [comment]
Are you sure you are using a passport? It does not work with the German identity card (Personalausweis).

**Comment by phaitonican** [comment]
Oh sorry, I tried it with German ID card. My bad i need get passport and then It should work thanks.

**Comment by phaitonican** [comment]
Oh sorry my bad, i used the German identity card (Personalausweis).
